services:
    app:
        build:
            args:
                user: sv1ft
                uid: 1000
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        container_name: travel-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travel
        depends_on:
            -   db
    db:
        image: mysql:5.7
        container_name: travel-db
        restart: unless-stopped
        volumes:
            - "../_db/mysql:/var/lib/mysql:rw"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        networks:
            - travel

    nginx:
        image: nginx:1.17-alpine
        container_name: travel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf:/etc/nginx/conf.d
        networks:
            - travel
        depends_on:
            -   app

networks:
    travel:
        driver: bridge
